# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: syscalls.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esyscalls.proto\x12\x11snapfaas.syscalls\"\x1c\n\x06\x43lause\x12\x12\n\nprincipals\x18\x01 \x03(\t\"7\n\tComponent\x12*\n\x07\x63lauses\x18\x01 \x03(\x0b\x32\x19.snapfaas.syscalls.Clause\"\x8d\x01\n\x07\x44\x63Label\x12\x32\n\x07secrecy\x18\x01 \x01(\x0b\x32\x1c.snapfaas.syscalls.ComponentH\x00\x88\x01\x01\x12\x34\n\tintegrity\x18\x02 \x01(\x0b\x32\x1c.snapfaas.syscalls.ComponentH\x01\x88\x01\x01\x42\n\n\x08_secrecyB\x0c\n\n_integrity\"\x1a\n\x07Request\x12\x0f\n\x07payload\x18\x01 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07payload\x18\x01 \x01(\t\"\x16\n\x07ReadKey\x12\x0b\n\x03key\x18\x01 \x01(\x0c\"/\n\x0fReadKeyResponse\x12\x12\n\x05value\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x42\x08\n\x06_value\"&\n\x08WriteKey\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c\"#\n\x10WriteKeyResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"b\n\nGithubRest\x12)\n\x04verb\x18\x01 \x01(\x0e\x32\x1b.snapfaas.syscalls.HttpVerb\x12\r\n\x05route\x18\x02 \x01(\t\x12\x11\n\x04\x62ody\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_body\"\"\n\x12GithubRestResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x11\n\x0fGetCurrentLabel\"\xcf\x02\n\x07Syscall\x12/\n\x08response\x18\x01 \x01(\x0b\x32\x1b.snapfaas.syscalls.ResponseH\x00\x12-\n\x07readKey\x18\x02 \x01(\x0b\x32\x1a.snapfaas.syscalls.ReadKeyH\x00\x12/\n\x08writeKey\x18\x03 \x01(\x0b\x32\x1b.snapfaas.syscalls.WriteKeyH\x00\x12=\n\x0fgetCurrentLabel\x18\x04 \x01(\x0b\x32\".snapfaas.syscalls.GetCurrentLabelH\x00\x12\x34\n\x0etaintWithLabel\x18\x05 \x01(\x0b\x32\x1a.snapfaas.syscalls.DcLabelH\x00\x12\x33\n\ngithubRest\x18\x06 \x01(\x0b\x32\x1d.snapfaas.syscalls.GithubRestH\x00\x42\t\n\x07syscall*\x1d\n\x08HttpVerb\x12\x07\n\x03GET\x10\x00\x12\x08\n\x04POST\x10\x01\x62\x06proto3')

_HTTPVERB = DESCRIPTOR.enum_types_by_name['HttpVerb']
HttpVerb = enum_type_wrapper.EnumTypeWrapper(_HTTPVERB)
GET = 0
POST = 1


_CLAUSE = DESCRIPTOR.message_types_by_name['Clause']
_COMPONENT = DESCRIPTOR.message_types_by_name['Component']
_DCLABEL = DESCRIPTOR.message_types_by_name['DcLabel']
_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_READKEY = DESCRIPTOR.message_types_by_name['ReadKey']
_READKEYRESPONSE = DESCRIPTOR.message_types_by_name['ReadKeyResponse']
_WRITEKEY = DESCRIPTOR.message_types_by_name['WriteKey']
_WRITEKEYRESPONSE = DESCRIPTOR.message_types_by_name['WriteKeyResponse']
_GITHUBREST = DESCRIPTOR.message_types_by_name['GithubRest']
_GITHUBRESTRESPONSE = DESCRIPTOR.message_types_by_name['GithubRestResponse']
_GETCURRENTLABEL = DESCRIPTOR.message_types_by_name['GetCurrentLabel']
_SYSCALL = DESCRIPTOR.message_types_by_name['Syscall']
Clause = _reflection.GeneratedProtocolMessageType('Clause', (_message.Message,), {
  'DESCRIPTOR' : _CLAUSE,
  '__module__' : 'syscalls_pb2'
  # @@protoc_insertion_point(class_scope:snapfaas.syscalls.Clause)
  })
_sym_db.RegisterMessage(Clause)

Component = _reflection.GeneratedProtocolMessageType('Component', (_message.Message,), {
  'DESCRIPTOR' : _COMPONENT,
  '__module__' : 'syscalls_pb2'
  # @@protoc_insertion_point(class_scope:snapfaas.syscalls.Component)
  })
_sym_db.RegisterMessage(Component)

DcLabel = _reflection.GeneratedProtocolMessageType('DcLabel', (_message.Message,), {
  'DESCRIPTOR' : _DCLABEL,
  '__module__' : 'syscalls_pb2'
  # @@protoc_insertion_point(class_scope:snapfaas.syscalls.DcLabel)
  })
_sym_db.RegisterMessage(DcLabel)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'syscalls_pb2'
  # @@protoc_insertion_point(class_scope:snapfaas.syscalls.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'syscalls_pb2'
  # @@protoc_insertion_point(class_scope:snapfaas.syscalls.Response)
  })
_sym_db.RegisterMessage(Response)

ReadKey = _reflection.GeneratedProtocolMessageType('ReadKey', (_message.Message,), {
  'DESCRIPTOR' : _READKEY,
  '__module__' : 'syscalls_pb2'
  # @@protoc_insertion_point(class_scope:snapfaas.syscalls.ReadKey)
  })
_sym_db.RegisterMessage(ReadKey)

ReadKeyResponse = _reflection.GeneratedProtocolMessageType('ReadKeyResponse', (_message.Message,), {
  'DESCRIPTOR' : _READKEYRESPONSE,
  '__module__' : 'syscalls_pb2'
  # @@protoc_insertion_point(class_scope:snapfaas.syscalls.ReadKeyResponse)
  })
_sym_db.RegisterMessage(ReadKeyResponse)

WriteKey = _reflection.GeneratedProtocolMessageType('WriteKey', (_message.Message,), {
  'DESCRIPTOR' : _WRITEKEY,
  '__module__' : 'syscalls_pb2'
  # @@protoc_insertion_point(class_scope:snapfaas.syscalls.WriteKey)
  })
_sym_db.RegisterMessage(WriteKey)

WriteKeyResponse = _reflection.GeneratedProtocolMessageType('WriteKeyResponse', (_message.Message,), {
  'DESCRIPTOR' : _WRITEKEYRESPONSE,
  '__module__' : 'syscalls_pb2'
  # @@protoc_insertion_point(class_scope:snapfaas.syscalls.WriteKeyResponse)
  })
_sym_db.RegisterMessage(WriteKeyResponse)

GithubRest = _reflection.GeneratedProtocolMessageType('GithubRest', (_message.Message,), {
  'DESCRIPTOR' : _GITHUBREST,
  '__module__' : 'syscalls_pb2'
  # @@protoc_insertion_point(class_scope:snapfaas.syscalls.GithubRest)
  })
_sym_db.RegisterMessage(GithubRest)

GithubRestResponse = _reflection.GeneratedProtocolMessageType('GithubRestResponse', (_message.Message,), {
  'DESCRIPTOR' : _GITHUBRESTRESPONSE,
  '__module__' : 'syscalls_pb2'
  # @@protoc_insertion_point(class_scope:snapfaas.syscalls.GithubRestResponse)
  })
_sym_db.RegisterMessage(GithubRestResponse)

GetCurrentLabel = _reflection.GeneratedProtocolMessageType('GetCurrentLabel', (_message.Message,), {
  'DESCRIPTOR' : _GETCURRENTLABEL,
  '__module__' : 'syscalls_pb2'
  # @@protoc_insertion_point(class_scope:snapfaas.syscalls.GetCurrentLabel)
  })
_sym_db.RegisterMessage(GetCurrentLabel)

Syscall = _reflection.GeneratedProtocolMessageType('Syscall', (_message.Message,), {
  'DESCRIPTOR' : _SYSCALL,
  '__module__' : 'syscalls_pb2'
  # @@protoc_insertion_point(class_scope:snapfaas.syscalls.Syscall)
  })
_sym_db.RegisterMessage(Syscall)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HTTPVERB._serialized_start=968
  _HTTPVERB._serialized_end=997
  _CLAUSE._serialized_start=37
  _CLAUSE._serialized_end=65
  _COMPONENT._serialized_start=67
  _COMPONENT._serialized_end=122
  _DCLABEL._serialized_start=125
  _DCLABEL._serialized_end=266
  _REQUEST._serialized_start=268
  _REQUEST._serialized_end=294
  _RESPONSE._serialized_start=296
  _RESPONSE._serialized_end=323
  _READKEY._serialized_start=325
  _READKEY._serialized_end=347
  _READKEYRESPONSE._serialized_start=349
  _READKEYRESPONSE._serialized_end=396
  _WRITEKEY._serialized_start=398
  _WRITEKEY._serialized_end=436
  _WRITEKEYRESPONSE._serialized_start=438
  _WRITEKEYRESPONSE._serialized_end=473
  _GITHUBREST._serialized_start=475
  _GITHUBREST._serialized_end=573
  _GITHUBRESTRESPONSE._serialized_start=575
  _GITHUBRESTRESPONSE._serialized_end=609
  _GETCURRENTLABEL._serialized_start=611
  _GETCURRENTLABEL._serialized_end=628
  _SYSCALL._serialized_start=631
  _SYSCALL._serialized_end=966
# @@protoc_insertion_point(module_scope)
