/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_princeton_sns_VSock */

#ifndef _Included_edu_princeton_sns_VSock
#define _Included_edu_princeton_sns_VSock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_princeton_sns_VSock
 * Method:    vsock_connect
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_edu_princeton_sns_VSock_vsock_1connect
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     edu_princeton_sns_VSock
 * Method:    vsock_read
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_princeton_sns_VSock_vsock_1read
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_princeton_sns_VSock
 * Method:    vsock_write
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_princeton_sns_VSock_vsock_1write
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     edu_princeton_sns_VSock
 * Method:    vscok_close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_princeton_sns_VSock_vscok_1close
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
